providers = ["node"]

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20", "corepack"]

[phases.install]
cmds = [
  "corepack enable pnpm",
  "pnpm install --frozen-lockfile"
]
cacheDirectories = ["~/.cache/pnpm"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"
